# Generated by Django 2.2.6 on 2019-10-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191011_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='presets',
            name='strong_desc',
        ),
    ]
