# Generated by Django 2.2.6 on 2019-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191011_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presets',
            name='img',
            field=models.ImageField(upload_to='presets/'),
        ),
    ]
