# Generated by Django 2.2.6 on 2019-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191011_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='presets',
            name='slug',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
