# Generated by Django 2.2.6 on 2019-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_presets_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presets',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
