# Generated by Django 2.2.6 on 2019-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='presets',
            name='bold_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presets',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presets',
            name='lot',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presets',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
