# Generated by Django 2.2.6 on 2019-10-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191015_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='presets',
            name='buy_href',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
